### ISSUE TITLE
Use a property to tag accounts that haven't confirmed mail

### ISSUE THREAD

**Issue by corp-0** [unitystation/central-command#13]
Right now the "active" property is used for this purpose. This is inconvenient because users are unable to login and don't get any prompt on why could that be. Instead use another bool property on Account to tag it as confirmed. While not confirmed, allow them to login but redirect them to a view telling them to confirm or resend the mail confirmation.

**Comment by Fogapod** [comment]
Not sure that this is necessary. Why can't you show user an error: `account does not exists or email is not confirmed`

**Comment by corp-0** [comment]
yep, that's also an option. We can explore what fits best

**Comment by Fogapod** [comment]
Having both `active` and `verified` is useful if you plan to have some way to deactivate accounts, but I don't see it in current implementation. `verified` could be enough

**Comment by corp-0** [comment]
there is a ``is_confirmed`` field for this purpose now
