### ISSUE TITLE
Improve error message for disabled account login

### ISSUE THREAD

**Issue by NoooneyDude** [unitystation/central-command#46]
- The error message when attempting a login on a disabled account could be improved:
`"error": "{'non_field_errors': [ErrorDetail(string='Unable to login with provided credentials.', code='invalid')]}`
"This account is disabled." would be more informative.

**Comment by NoooneyDude** [comment]
I had to learn this all over again : P

**Comment by corp-0** [comment]
hehe. From what I experienced lately, the newest version of django actually differentiates between non-existent and deactivated accounts, so the error would natively be more descriptive. Keep this open until I update though

**Comment by corp-0** [comment]
already fixed
